# Use a lightweight OpenJDK image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the compiled JAR file into the container
COPY src/ExpenseappApplication.java /app/ExpenseappApplication.java

#complie code
RUN javac ExpenseAppApplication.java

# Expose port 8080 (default for Spring Boot)
EXPOSE 8080

# Command to run the application
CMD["Java" "ExpenseappApplication"]
