# Use a lightweight OpenJDK image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the compiled JAR file into the container
COPY src/ExpenseappApplication.java /app/ExpenseappApplication.java

#complie code
RUN javac ExpenseappApplication.java

# Command to run the application
CMD["java", "ExpenseappApplication"]
